# Generated by Django 6.0.1 on 2026-01-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portforlio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
