# Generated by Django 6.0.1 on 2026-01-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portforlio_app', '0003_framework_stack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cv', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
