# Generated by Django 6.0.1 on 2026-01-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portforlio_app', '0004_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttitle', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='about/')),
                ('body', models.TextField()),
            ],
        ),
    ]
