# Generated by Django 6.0.1 on 2026-01-12 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portforlio_app', '0005_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='ttitle',
            new_name='title',
        ),
    ]
